import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
page.on('pageerror', (err) => console.log('PAGEERROR', err.message));
await page.goto('http://127.0.0.1:5173/', { waitUntil: 'domcontentloaded', timeout: 20000 });
await page.waitForTimeout(2500);
await page.click('text=+4 монстри');
await page.waitForTimeout(1500);
await page.screenshot({ path: 'debug-gallery-plus4.png', animations: 'disabled' });
console.log('plus4 screenshot ok');
await browser.close();
