import type { Trait, VoiceFxPresetId } from '../core/types';

/**
 * Monster-voice FX — character comes from pitch / formant / grit,
 * NOT from hall reverb or echo (those make it sound like a podcast, not a creature).
 */
export interface VoiceFxPreset extends Trait {
  id: VoiceFxPresetId;
  /** Relative pitch hint (~-1..1), applied with playbackRate */
  pitch: number;
  playbackRate: number;
  lowpass?: number;
  highpass?: number;
  /** Peaking EQ Hz for formant / throat color */
  formant?: number;
  formantGain?: number;
  formantQ?: number;
  distortion?: number;
  bitcrush?: number;
  /** Second layer at this rate (growl / alien double) — 0 = off */
  dualRate?: number;
  dualGain?: number;
  /** Tiny room only (0..0.2) — never hall */
  room?: number;
  /** Master gain */
  gain?: number;
}

export const STRENGTHS: Trait[] = [
  { id: 'fearless', label: 'Fearless', labelUk: 'безстрашний', description: 'гучний, сміливий' },
  { id: 'charismatic', label: 'Charismatic', labelUk: 'харизматичний', description: 'магнетичний' },
  { id: 'hypnoticVoice', label: 'Hypnotic', labelUk: 'гіпнотичний', description: 'монотонно-чарівний' },
  { id: 'quickWit', label: 'Quick Wit', labelUk: 'дотепний', description: 'швидкі рими' },
  { id: 'streetSmart', label: 'Street Smart', labelUk: 'вулиця', description: 'сленг, punchlines' },
  { id: 'loyal', label: 'Loyal', labelUk: 'вірний', description: 'теплі bar' },
  { id: 'creative', label: 'Creative', labelUk: 'креативний', description: 'метафори' },
  { id: 'intimidating', label: 'Intimidating', labelUk: 'страшний', description: 'агресивна подача' },
  { id: 'resilient', label: 'Resilient', labelUk: 'стійкий', description: 'не здається' },
  { id: 'charming', label: 'Charming', labelUk: 'чарівний', description: 'флірт у репі' },
  { id: 'observant', label: 'Observant', labelUk: 'уважний', description: 'деталі' },
  { id: 'improviser', label: 'Improviser', labelUk: 'імпровізатор', description: 'random insert' },
  { id: 'rhythmMaster', label: 'Rhythm Master', labelUk: 'ритм', description: 'чіткий flow' },
  { id: 'loudLungs', label: 'Loud Lungs', labelUk: 'легені', description: 'високий gain' },
  { id: 'mimic', label: 'Mimic', labelUk: 'мімік', description: 'копіює фрази' },
  { id: 'storyteller', label: 'Storyteller', labelUk: 'оповідач', description: 'довші куплети' },
  { id: 'unpredictable', label: 'Unpredictable', labelUk: 'незрозумілий', description: 'різкий темп' },
  { id: 'magnetic', label: 'Magnetic', labelUk: 'магніт', description: 'call-and-response' },
  { id: 'cunning', label: 'Cunning', labelUk: 'хитрий', description: 'подвійні сенси' },
  { id: 'optimistic', label: 'Optimistic', labelUk: 'оптиміст', description: 'позитивні bar' },
];

export const WEAKNESSES: Trait[] = [
  { id: 'shy', label: 'Shy', labelUk: 'соромʼязливий', description: 'тихо, коротко' },
  { id: 'forgetful', label: 'Forgetful', labelUk: 'забудькуватий', description: 'emm…' },
  { id: 'mumbles', label: 'Mumbles', labelUk: 'бурмоче', description: 'ковтає кінцівки' },
  { id: 'stageFright', label: 'Stage Fright', labelUk: 'страх сцени', description: 'falsetto' },
  { id: 'trustsTooEasy', label: 'Trusting', labelUk: 'довірливий', description: 'наївні bar' },
  { id: 'hotTempered', label: 'Hot Tempered', labelUk: 'гарячий', description: 'крики mid-bar' },
  { id: 'lazy', label: 'Lazy', labelUk: 'лінивий', description: 'повільний flow' },
  { id: 'jealous', label: 'Jealous', labelUk: 'заздрісний', description: 'diss' },
  { id: 'overshares', label: 'Oversharer', labelUk: 'балакучий', description: 'довгі bar' },
  { id: 'monotone', label: 'Monotone', labelUk: 'монотонний', description: 'flat delivery' },
  { id: 'stutterStress', label: 'Stutter', labelUk: 'заїка', description: 'я-я-я' },
  { id: 'distracted', label: 'Distracted', labelUk: 'розсіяний', description: 'side topic' },
  { id: 'blunt', label: 'Blunt', labelUk: 'прямий', description: 'без фільтра' },
  { id: 'dramaticPause', label: 'Dramatic Pause', labelUk: 'паузи', description: '… часто' },
  { id: 'nameForgetter', label: 'Name Forgetter', labelUk: 'забуває імена', description: 'ей ти' },
  { id: 'alwaysHungry', label: 'Always Hungry', labelUk: 'голодний', description: 'food metaphors' },
  { id: 'superstitious', label: 'Superstitious', labelUk: 'перестрах', description: 'табу слова' },
  { id: 'paranoid', label: 'Paranoid', labelUk: 'параноїк', description: 'шепіт + loud' },
  { id: 'oversleepy', label: 'Oversleepy', labelUk: 'сонний', description: 'yawn' },
  { id: 'competitive', label: 'Competitive', labelUk: 'конкурент', description: 'diss-heavy' },
];

export const SPEECH_STYLES: Trait[] = [
  { id: 'staccato', label: 'Staccato', labelUk: 'staccato', description: 'короткі удари' },
  { id: 'drawl', label: 'Drawl', labelUk: 'drawl', description: 'розтягнуті голосні' },
  { id: 'whisperRap', label: 'Whisper Rap', labelUk: 'whisper', description: 'тихий flow' },
  { id: 'shoutRap', label: 'Shout Rap', labelUk: 'shout', description: 'крик' },
  { id: 'mumbleFlow', label: 'Mumble Flow', labelUk: 'mumble', description: 'каша слів' },
  { id: 'theatrical', label: 'Theatrical', labelUk: 'театр', description: 'О! І ось!' },
  { id: 'nurseryRhyme', label: 'Nursery Rhyme', labelUk: 'дитячий', description: 'рима кожен 2-й' },
  { id: 'trashTalk', label: 'Trash Talk', labelUk: 'trash', description: 'diss mode' },
  { id: 'philosophicalBars', label: 'Philosophical', labelUk: 'філософ', description: 'питання' },
  { id: 'nonsenseSyllables', label: 'Nonsense', labelUk: 'nonsense', description: 'skrrt-bap' },
  { id: 'callAndResponse', label: 'Call & Response', labelUk: 'call-response', description: 'де монстри?' },
  { id: 'doubleTime', label: 'Double Time', labelUk: 'double-time', description: 'швидко' },
  { id: 'slowTrap', label: 'Slow Trap', labelUk: 'slow trap', description: 'паузи' },
  { id: 'singSong', label: 'Sing Song', labelUk: 'sing-song', description: 'мелодійно' },
  { id: 'brokenGrammar', label: 'Broken Grammar', labelUk: 'граматика', description: 'навмисні помилки' },
  { id: 'alliteration', label: 'Alliteration', labelUk: 'алітерація', description: 'повтор приголосних' },
  { id: 'questionEverything', label: 'Questions', labelUk: 'питання', description: 'кожен bar?' },
  { id: 'thirdPersonSelf', label: 'Third Person', labelUk: '3-тя особа', description: 'Він каже' },
  { id: 'oldWiseMonster', label: 'Old Wise', labelUk: 'старий', description: 'архаїзми' },
  { id: 'glitchStutter', label: 'Glitch', labelUk: 'glitch', description: 'gl-glitch' },
];

/** Monster-first presets — dry character, almost no echo. */
export const VOICE_FX_PRESETS: VoiceFxPreset[] = [
  {
    id: 'deepCave',
    label: 'Bog Beast',
    labelUk: 'болотний',
    description: 'низький, глухий',
    pitch: -0.4,
    playbackRate: 0.72,
    lowpass: 2400,
    formant: 280,
    formantGain: 8,
    formantQ: 2,
    distortion: 0.22,
    gain: 1.05,
  },
  {
    id: 'chipmunkInverse',
    label: 'Squeaky Imp',
    labelUk: 'піщун',
    description: 'писклявий імп',
    pitch: 0.45,
    playbackRate: 1.35,
    highpass: 350,
    formant: 2200,
    formantGain: 6,
    formantQ: 3,
    gain: 0.95,
  },
  {
    id: 'underwater',
    label: 'Gurgle',
    labelUk: 'булькає',
    description: 'мокрий глоток',
    pitch: -0.15,
    playbackRate: 0.88,
    lowpass: 1600,
    highpass: 120,
    formant: 450,
    formantGain: 10,
    formantQ: 4,
    distortion: 0.12,
    gain: 1,
  },
  {
    id: 'radioStatic',
    label: 'Static Ghoul',
    labelUk: 'радіо-привид',
    description: 'шипіння + grit',
    pitch: 0.05,
    playbackRate: 1.02,
    highpass: 500,
    lowpass: 3800,
    distortion: 0.35,
    bitcrush: 8,
    gain: 0.9,
  },
  {
    id: 'demonGrowl',
    label: 'Demon Growl',
    labelUk: 'демон',
    description: 'подвійний низький',
    pitch: -0.5,
    playbackRate: 0.68,
    dualRate: 0.55,
    dualGain: 0.45,
    lowpass: 1800,
    formant: 220,
    formantGain: 10,
    formantQ: 2.5,
    distortion: 0.48,
    gain: 1.1,
  },
  {
    id: 'echoHall',
    label: 'Hiss Whisper',
    labelUk: 'шипить',
    description: 'тихий шип, без залу',
    pitch: 0.1,
    playbackRate: 1.08,
    highpass: 700,
    lowpass: 4500,
    formant: 3200,
    formantGain: 5,
    formantQ: 5,
    distortion: 0.08,
    gain: 0.85,
  },
  {
    id: 'telephone',
    label: 'Tin Goblin',
    labelUk: 'бляшаний',
    description: 'вузький tin',
    pitch: 0.12,
    playbackRate: 1.1,
    highpass: 400,
    lowpass: 2800,
    formant: 1600,
    formantGain: 7,
    formantQ: 6,
    distortion: 0.28,
    gain: 1,
  },
  {
    id: 'bitcrushed',
    label: 'Pixel Critter',
    labelUk: 'піксель',
    description: 'ломаний 8-bit',
    pitch: 0.08,
    playbackRate: 1.05,
    bitcrush: 5,
    distortion: 0.3,
    highpass: 200,
    lowpass: 5000,
    gain: 0.95,
  },
  {
    id: 'reverseReverbTail',
    label: 'Rasp Throat',
    labelUk: 'хрип',
    description: 'хриплий горло',
    pitch: -0.2,
    playbackRate: 0.85,
    formant: 600,
    formantGain: 9,
    formantQ: 1.5,
    distortion: 0.4,
    lowpass: 3000,
    gain: 1.05,
  },
  {
    id: 'megaphone',
    label: 'Yell Beast',
    labelUk: 'ор',
    description: 'агресивний mid',
    pitch: 0.05,
    playbackRate: 1.04,
    highpass: 400,
    lowpass: 4200,
    formant: 1100,
    formantGain: 8,
    formantQ: 2,
    distortion: 0.42,
    gain: 1.15,
  },
  {
    id: 'hollowPipe',
    label: 'Hollow Skull',
    labelUk: 'порожній',
    description: 'резонанс черепа',
    pitch: -0.18,
    playbackRate: 0.9,
    formant: 900,
    formantGain: 12,
    formantQ: 8,
    highpass: 180,
    lowpass: 3200,
    gain: 1,
  },
  {
    id: 'wetMouth',
    label: 'Slobber',
    labelUk: 'слинявий',
    description: 'слиз + мʼякий',
    pitch: -0.08,
    playbackRate: 0.94,
    lowpass: 2800,
    formant: 500,
    formantGain: 7,
    formantQ: 3,
    distortion: 0.15,
    gain: 1,
  },
  {
    id: 'rustyRobot',
    label: 'Rusty Bot',
    labelUk: 'іржавий бот',
    description: 'метал + crush',
    pitch: 0.18,
    playbackRate: 1.12,
    bitcrush: 6,
    distortion: 0.45,
    formant: 1800,
    formantGain: 4,
    formantQ: 4,
    highpass: 300,
    gain: 0.95,
  },
  {
    id: 'windTunnel',
    label: 'Breathy Blob',
    labelUk: 'дихає',
    description: 'повітряний',
    pitch: 0.15,
    playbackRate: 1.08,
    highpass: 600,
    lowpass: 5500,
    formant: 2500,
    formantGain: 4,
    formantQ: 2,
    gain: 0.9,
  },
  {
    id: 'cathedral',
    label: 'Ancient One',
    labelUk: 'древній',
    description: 'повільний глибокий',
    pitch: -0.35,
    playbackRate: 0.75,
    lowpass: 2000,
    formant: 250,
    formantGain: 9,
    formantQ: 2,
    distortion: 0.18,
    room: 0.12,
    gain: 1.05,
  },
  {
    id: 'vinylCrackle',
    label: 'Dust Mite',
    labelUk: 'пиловий',
    description: 'ло-фай крихта',
    pitch: 0.1,
    playbackRate: 1.06,
    bitcrush: 9,
    highpass: 400,
    lowpass: 4500,
    distortion: 0.2,
    gain: 0.9,
  },
  {
    id: 'phaseShift',
    label: 'Twitch',
    labelUk: 'твіч',
    description: 'нервовий pitch',
    pitch: 0.22,
    playbackRate: 1.18,
    dualRate: 1.28,
    dualGain: 0.25,
    formant: 1400,
    formantGain: 5,
    formantQ: 3,
    gain: 0.95,
  },
  {
    id: 'subBassBoost',
    label: 'Sub Golem',
    labelUk: 'голем',
    description: 'саб + вага',
    pitch: -0.42,
    playbackRate: 0.7,
    lowpass: 1400,
    formant: 160,
    formantGain: 11,
    formantQ: 1.8,
    distortion: 0.25,
    gain: 1.1,
  },
  {
    id: 'nasalPinch',
    label: 'Nasal Critter',
    labelUk: 'носовий',
    description: 'носовий писк',
    pitch: 0.28,
    playbackRate: 1.22,
    formant: 1800,
    formantGain: 11,
    formantQ: 7,
    highpass: 500,
    lowpass: 4800,
    gain: 0.95,
  },
  {
    id: 'alienChorus',
    label: 'Alien Double',
    labelUk: 'чужий',
    description: 'два шари, без залу',
    pitch: 0.2,
    playbackRate: 1.1,
    dualRate: 0.92,
    dualGain: 0.55,
    formant: 2400,
    formantGain: 6,
    formantQ: 4,
    highpass: 250,
    gain: 1,
  },
];

export function getFxPreset(id: VoiceFxPresetId): VoiceFxPreset {
  return VOICE_FX_PRESETS.find((p) => p.id === id) ?? VOICE_FX_PRESETS[0]!;
}
